### ISSUE TITLE
Create install and build script for CircleCI

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#65]
Create install and build script for CircleCI

**Comment by guylepage3** [comment]
Resolved current failing "hello world" script...

```
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-go
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: echo "hello world"
```
